blog/apps/user/urls.py
from django.urls import path
import apps.user.views as views

app_name = "user"

urlpatterns = [
    path('profile/', views.UserProfileView.as_view(), name="user_profile"),
    path('auth/register/', views.RegisterView.as_view(), name="auth_register"),
    path('auth/login/', views.LoginView.as_view(), name="auth_login"),
    path('auth/logout/', views.LogoutView.as_view(), name="auth_logout"),
    path('update/', views.UserUpdateView.as_view(), name="user_update"),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView, AboutView, ContactView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('posts/', include('apps.post.urls', namespace='post')),
    path('users/', include('apps.user.urls', namespace='user')),
    path('section/about/', AboutView.as_view(), name='section_about'),
    path('section/contact/', ContactView.as_view(), name='section_contact'),
    path('contactuss/', include('apps.contactus.urls', namespace='contactus')),
]

if settings.DEBUG:
 from django.conf.urls.static import static
 # Sirviendo archivos estáticos
 urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
 # Sirviendo archivos media
 urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)
 

blog/apps/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import os
import uuid


def get_avatar_filename(instance, filename):
    # imagen3121212 .png imagen3121212.png
    base_filename, file_extension = os.path.splitext(filename)
    # user_1_avatar.png
    new_filename = f"user_{instance.id}_avatar{file_extension}"
    # user/avatar/user_1_avatar.png
    return os.path.join('user/avatar/', new_filename)


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    alias = models.CharField(max_length=30, blank=True)
    avatar = models.ImageField(upload_to=get_avatar_filename, default='user/default/avatar_default.jpg')

    @property 
    def is_collaborator(self): 
        return self.groups.filter(name='Collaborators').exists() 
    
    @property 
    def is_admin(self): 
        return self.groups.filter(name='Admins').exists() 

    @property 
    def is_registered(self): 
        return self.groups.filter(name='Registered').exists() 
    
    @property
    def role(self):
        if self.is_superuser:
            return 'Superadmin'
        elif self.is_admin:
            return 'Administrador'
        elif self.is_collaborator:
            return 'Colaborador'
        elif self.is_registered:
            return 'Registrado'
        else:
            return 'Visitante'

blog/apps/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from apps.user.models import User
from django.contrib.auth import authenticate

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for field_name in ['username', 'password1', 'password2']:
            self.fields[field_name].widget.attrs.update({
                'class': 'mt-1 block w-full p-2 border border-gray-300 rounded-md bg-white text-black'
            })
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("El nombre de usuario ya está en uso.")
        return username


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=254,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Usuario'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Contraseña'}
        )
    )

    def __init__(self, *args, **kwargs):  # El método debe tener doble guion bajo al principio y al final
        super(LoginForm, self).__init__(*args, **kwargs)
        # Actualizando atributos de los campos
        self.fields['username'].widget.attrs.update({
            'class': 'mt-1 block w-full p-2 border border-gray-300 rounded-md bg-white text-black'
        })
        self.fields['password'].widget.attrs.update({
            'class': 'mt-1 block w-full p-2 border border-gray-300 rounded-md bg-white text-black'
        })
    
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError("No hay ningún usuario registrado con ese nombre.")
        return username

    def clean_password(self):
        password = self.cleaned_data.get("password")
        username = self.cleaned_data.get("username")

        if username and password:
            # Autenticar al usuario con ambos campos
            user = authenticate(username=username, password=password)
            if user is None:
                # Asocia el error al campo de la contraseña
                raise forms.ValidationError("Contraseña incorrecta.")

        return password


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'avatar'] 
       
    def __init__(self, *args, **kwargs):
        super(UpdateUserForm, self).__init__(*args, **kwargs)
        for field_name in ['first_name', 'last_name', 'email']:
            self.fields[field_name].widget.attrs.update({
                'class': 'border border-gray-300 p-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-300 max-w-xs w-full h-10'
            })

blog/apps/user/views.py
from django.views.generic import TemplateView, CreateView, UpdateView
from django.contrib.auth.views import LoginView as LoginViewDjango, LogoutView as LogoutViewDjango
from apps.user.forms import RegisterForm, LoginForm, UpdateUserForm
from django.contrib.auth.models import Group
from django.urls import reverse_lazy
from django.conf import settings
from apps.user.models import User

class UserProfileView(TemplateView):
    template_name = 'user/user_profile.html'

    def get_context_data(self, **kwargs):
        # Llama al contexto de la clase padre
        context = super().get_context_data(**kwargs)
        # Agrega el usuario actual al contexto
        context['user_profile'] = self.request.user
        # Agrega MEDIA_URL al contexto
        context['MEDIA_URL'] = settings.MEDIA_URL
        return context
    

class RegisterView(CreateView):
    template_name = 'auth/auth_register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('user:auth_login')  # Redirige al home una vez registrado

    def form_valid(self, form):
        # Llama a la función form_valid de la clase padre y guarda el usuario
        response = super().form_valid(form)

        # Asignar el grupo 'Registered' al usuario recién creado
        registered_group = Group.objects.get(name='Registered')
        self.object.groups.add(registered_group)

        # En caso de ser necesario, se le puede asignar explícitamente los permisos del grupo al usuario
        # for permission in registered_group.permissions.all():
        #     self.object.user_permissions.add(permission)

        return response
    
    def form_invalid(self, form):
        return super().form_invalid(form)  # Esto volverá a mostrar el formulario con errores

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['color_bg_form'] = 'bg-[#3D190C]'
        context['color_bg'] = 'bg-[#DCA278]'
        return context
    

class LoginView(LoginViewDjango):
    template_name = 'auth/auth_login.html'
    authentication_form = LoginForm

    def get_success_url(self):
        return reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['color_bg_form'] = 'bg-[#451121]'
        context['color_bg'] = 'bg-[#DCA278]'
        return context
    

class LogoutView(LogoutViewDjango):
    def get_success_url(self):
        return reverse_lazy('home')
    

class UserUpdateView(UpdateView):
    template_name = 'user/user_update.html'
    model = User
    form_class = UpdateUserForm
    success_url = reverse_lazy('user:user_profile')  # Redirige al perfil después de la actualización

    def get_object(self):
        return self.request.user 

blog/templates/user/user_profile.html
{% extends 'layouts/user_layout.html' %}

{% block title %}Perfil de Usuario{% endblock %}

{% block content %}
    <main class="container mx-auto my-16">
            <div class="bg-white shadow-lg rounded-lg overflow-hidden max-w-4xl mx-auto w-full grid grid-cols-1 md:grid-cols-2">
                <div class="relative">
                    {% if user.avatar %}
                        <img class="w-full h-96 object-cover" src="{{ user.avatar.url }}" alt="Profile Image">
                    {% else %}
                        <img class="w-full h-96 object-cover" src="{{ MEDIA_URL }}user/default/avatar_default.jpg" alt="Default Profile Image">
                    {% endif %}
                    <div class="absolute bottom-0 left-0 right-0 bg-[#1b3030] text-center p-4">
                        <h2 class="text-white text-xl font-normal font-onest">Hola, <span class="text-white text-2xl font-bold font-onest">{{ user_profile.username }}</span></h2>
                    </div>
                </div>

                <div class="p-8 flex flex-col justify-center font-onest">
                    <p class="text-gray-600 text-lg mb-4">
                        <span class="text-black  text-lg font-bold">Usuario:</span> 
                        <span class="p-2">{{ user.username }}</span> 
                    </p>
                    <p class="text-gray-600 text-lg mb-4">
                        <span class="text-black text-lg font-bold">Nombre:</span> 
                        <span class="p-2">{{ user.first_name }}</span> 
                    </p>
                    <p class="text-gray-600 mb-4">
                        <span class="text-black text-lg font-bold">Apellido:</span> 
                        <span class="p-2">{{ user.last_name }}</span> 
                    </p>
                    <p class="text-gray-600 mb-4">
                        <span class="text-black text-lg font-bold">Email:</span> 
                        <span class="p-2">{{ user.email }}</span> 
                    </p>
                    <p class="text-gray-600 mb-4">
                        <span class="text-black text-lg font-bold">Creado:</span> 
                        <span class="p-2">{{ user.date_joined }}</span> 
                    </p>
        
                    <p class="text-gray-600 mb-4">
                        <span class="text-black text-lg font-bold">Tipo de usuario:</span> 
                        <span class="p-2">{{ user.role}}</span> 
                    </p>
                  
                    
                    
                    <p class="text-gray-600 mb-4">
                        <span class="text-black text-lg font-bold">Ultimo ingreso:</span> {{ user.last_login }}
                    </p>

                    <div class="flex justify-between mt-6">
                        <a href="{% url 'user:user_update' %}" class="px-3 py-2 text-sm font-medium text-center justify-between gap-2 inline-flex items-center text-white bg-blue-900 rounded-lg hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-800 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
                            </svg>
                            Editar
                        </a>
                        <div class="flex justify-center">
                            <a href="{% url 'home' %}"
                               class="px-3 py-2 text-sm font-medium text-center justify-between gap-2 inline-flex items-center text-white bg-blue-900 rounded-lg hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-800 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                                 Volver
                             </a>
                        </div>       
                    </div>
                   
                </div>
            </div>

    </main>
{% endblock %}

blog/templates/user/user_update.html
{% extends 'layouts/user_layout.html' %}

{% block title %}Perfil de Usuario{% endblock %}

{% block content %}
<main class="container mx-auto my-16">
    <div class="bg-white shadow-lg rounded-lg overflow-hidden max-w-4xl mx-auto w-full grid grid-cols-1 md:grid-cols-2">
        <div class="relative">
            {% if user.avatar %}
                <img class="w-full h-96 object-cover" src="{{ user.avatar.url }}" alt="Profile Image">
            {% else %}
                <img class="w-full h-96 object-cover" src="{{ MEDIA_URL }}user/default/avatar_default.jpg" alt="Default Profile Image">
            {% endif %}
            <div class="absolute bottom-0 left-0 right-0 bg-[#1b3030] text-center p-4">
                <h2 class="text-white text-xl font-normal font-onest">
                    Hola, <span class="text-white text-2xl font-bold font-onest">{{ user.username }}</span>
                </h2>
            </div>
        </div>

        <div class="p-8 flex flex-col justify-center font-onest">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                <!-- Campo Usuario (no editable) -->
                <p class="text-gray-600 text-lg mb-4">
                    <span class="text-black text-lg font-bold">Usuario:</span> {{ user.username }}
                </p>

                <!-- Campo Nombre -->
                <div class="flex items-center mb-2">
                    <label for="first_name" class="block text-black text-lg font-bold mr-2">Nombre:</label>                    
                    {{ form.first_name }}

                </div>

                <!-- Campo Apellido -->
                <div class="flex items-center mb-2">
                    <label for="last_name" class="block text-black text-lg font-bold mr-2">Apellido:</label>
                    {{ form.last_name }}
                
                </div>

                <!-- Campo Email -->
                <div class="flex items-center mb-2">
                    <label for="email" class="block text-black text-lg font-bold mr-2">Email:</label>
                        {{ form.email }}
                </div>

                <div class="mb-4">
                    <label class="block text-black text-lg font-bold mb-2" for="avatar">Cambiar Avatar:</label>
                    {{ form.avatar }}
                </div>

                <!-- Botón para enviar los cambios -->
                <div class="flex justify-between mt-6">
                    <button type="submit" class="px-3 py-2 text-sm font-medium text-center justify-between gap-2 inline-flex items-center text-white bg-blue-900 rounded-lg hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-800 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
                        </svg>
                        Guardar Cambios
                    </button>

                    <div class="flex justify-center">
                        <a href="{% url 'user:user_profile' %}"
                           class="px-3 py-2 text-sm font-medium text-center justify-between gap-2 inline-flex items-center text-white bg-blue-900 rounded-lg hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-800 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                             Cancelar
                         </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</main>
{% endblock %}