blog-django/blog/apps/post/urls.py
from django.urls import path
import apps.post.views as views

app_name = 'post'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('create', views.PostCreateView.as_view(), name='post_create'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/update', views.PostUpdateView.as_view(), name='post_update'),
    path('<slug:slug>/delete', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/<slug:slug>/comments/create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comments/<uuid:pk>/update/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comments/<uuid:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
]

blog-django/blog/apps/user/urls.py
from django.urls import path
import apps.user.views as views

app_name = "user"

urlpatterns = [
    path('profile/', views.UserProfileView.as_view(), name="user_profile"),
    path('auth/register/', views.RegisterView.as_view(), name="auth_register"),
    path('auth/login/', views.LoginView.as_view(), name="auth_login"),
    path('auth/logout/', views.LogoutView.as_view(), name="auth_logout"),
]

blog-django/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView, AuthLoginView, AuthRegisterView, AboutView, ContactView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('posts/', include('apps.post.urls', namespace='post')),
    path('users/', include('apps.user.urls', namespace='user')),
    #path('auth/login/', AuthLoginView.as_view(), name='auth_login'),
    #path('auth/register/', AuthRegisterView.as_view(), name='auth_register'),
    path('section/about/', AboutView.as_view(), name='section_about'),
    path('section/contact/', ContactView.as_view(), name='section_contact'),
]

if settings.DEBUG:
 from django.conf.urls.static import static
 # Sirviendo archivos estáticos
 urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
 # Sirviendo archivos media
 urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)
 
 '''
 from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView, AboutView 
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about')
    path('posts/', include('apps.post.urls', namespace='post')),
    path('user/', include('apps.user.urls', namespace='user'))
]

if settings.DEBUG:
 from django.conf.urls.static import static
 # Sirviendo archivos estáticos
 urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
 # Sirviendo archivos media
 urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)
 '''

blog-django/blog/templates/components/ui/blockDecoration.html
<div class="lg:h-[180px] lg:relative w-full bg-[#3C3D37]">
        {% include 'components/ui/flag.html' %}
</div>

blog-django/blog/templates/components/ui/button.html
<button type="button" class="py-2.5 px-5 m-2 uppercase text-lg font-onest font-medium text-gray-900 focus:outline-none bg-white rounded-full border border-gray-200 hover:bg-gray-100 hover:text-blue-600 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
    {{ name }}
</button>

blog-django/blog/templates/components/ui/buttonLogin.html
<a href="{% url 'user:auth_login' %}" class="w-[200px] h-[50px] font-onest text-md bg-[#17153B] hover:bg-blue-800 text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-[18px] px-5 py-2.5 text-center inline-flex items-center me-2">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.75" stroke="currentColor" class="w-8 h-8 mr-2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
    </svg>
    Iniciar sesión
</a>

blog-django/blog/templates/components/ui/card.html
{% load static %}
<article class="max-w-sm bg-gray-100 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 overflow-hidden font-onest p-2">
  <div class="p-2">
    <h2 class="text-lg font-bold text-white uppercase">{{ title }}</h2>
  </div>
  <img class="w-full h-56 object-cover rounded-lg" src="{% static 'media/user/Wall.png' %}" alt="logo">
  <div class="mt-4 shadow dark:bg-gray-800 dark:border-gray-700 font-onest">
    <div class="bg-[#34455d] p-4 rounded-lg shadow-lg">
      <h3 class="text-md font-semibold text-white">{{ description }}</h3>
      <p class="text-sm text-gray-300">{{ date }}</p>
    </div>
  </div>
  <div class="px-4 py-2 text-gray-500 flex justify-between text-sm">
      <p>Comentarios {{ allow_comments }}</p>
      <p class="text-sm text-teal-600">@{{ user }}</p>
  </div>
    <div class="flex justify-end items-center gap-2 mt-2">
        <a href="{% url 'post:post_detail' slug=post.slug %}" class="px-3 py-2 text-sm font-medium text-center justify-between gap-2 inline-flex items-center text-white bg-blue-900 rounded-lg hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-800 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 24" stroke-width="1.5" stroke="currentColor" class="size-4">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
              <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
            </svg>
            Ver
        </a>
        <a href="{% url 'post:post_delete' slug=post.slug %}" class="mt-2 text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-3 py-2 text-center me-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900">Eliminar</a>
    </div>

</article>

blog-django/blog/templates/components/ui/card_about.html
{% load static %}
<div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <img class="rounded-t-lg" src="{% static 'media/user/' %}{{ image_name }}" alt="image" />
    <div class="p-5">
        <p class="mb-3 font-normal font-onest lg:text-sm sm:text-[18px] text-gray-700 dark:text-gray-400">{{ description }} </p>
    </div>
</div>

blog-django/blog/templates/components/ui/description.html
<p class="grid gap-2 place-content-center text-4xl h-[530px] mt-20 text-white font-onest font-light">
    ¡Visitar los festivales y eventos del Chaco es una experiencia única que no te podés perder! Es el lugar perfecto para sumergirte en la cultura, disfrutar de la música en vivo, la gastronomía local, y conocer la calidez de su gente.
    <span>
        ¡Es la excusa ideal para desconectar de la rutina y vivir momentos inolvidables en un entorno natural impresionante!
    </span>
</p>

blog-django/blog/templates/components/ui/developCard.html
<article class="grid place-items-center">
   <svg width="80" height="80" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" clip-rule="evenodd" d="M87.3749 147.217C87.3749 157.436 81.0804 172.918 61.1561 172.886H36V83H61.6874C80.9015 83 87.3641 98.4608 87.3695 108.685L87.3749 147.217ZM62.582 99.8189C64.6856 99.8189 66.7946 100.607 68.8982 102.182C70.9963 103.757 72.0535 106.126 72.0589 109.277V147.114C72.0589 150.27 71.0071 152.633 68.9036 154.209C66.8 155.784 64.691 156.572 62.5874 156.572H53.1268V99.8189H62.582Z" fill="yellow"/>
        <path d="M141.959 99.0529H113.073V119.924H130.731V135.988H113.073V156.854H141.965V172.918H108.253C102.203 173.076 97.1717 168.284 97.0199 162.222V94.2561C96.8735 88.1989 101.661 83.1684 107.706 83.0163H141.965L141.959 99.0529Z" fill="yellow"/>
        <path d="M198.149 161.684C190.992 178.389 178.17 175.064 172.429 161.684L151.539 83.0217H169.197L185.305 144.8L201.336 83.0217H219L198.149 161.684Z" fill="yellow"/>
    </svg>
    <div class="font-onest">
        <strong class="flex justify-center items-center text-md text-teal-900 ">{{ name }}</strong>
        <p class="text-xs text-slate-300">{{ email }}</p>
    </div>
</article>

blog-django/blog/templates/components/ui/flag.html
<div class="lg:absolute flex items-center justify-center h-auto w-full py-8 lg:w-[1053px] lg:h-[225px] bg-gray-200 lg:top-1/2 lg:left-1/2 lg:transform lg:-translate-x-1/2 lg:top-20">
  <div class="text-center">
    <h1 class="text-[48px] lg:text-[96px] font-normal text-[#3C3D37] tracking-wider font-splash">CHACO</h1>
    <p class="mt-2 text-[16px] lg:text-[20px] font-medium text-[#3C3D37] font-slackey">Festivales, Diversión y Cultura</p>
  </div>
</div>

blog-django/blog/templates/components/ui/logo.html
{% load static %}

<a href="{% url 'home' %}" class="flex gap-2">
    <img src="{% static 'media/user/logo-img.png' %}" alt="logo" class="w-20 h-20">
    <div class="grid gap-0 mt-4">
        <span class="flex justify-center items-center font-slackey lg:text-3xl text-[18px] font-regular uppercase tracking-widest">Festivales</span>
        <p class="flex justify-start lg:text-sm text-[13px] mb-4 font-onest">Provincia del Chaco</p>
    </div>
</a>

blog-django/blog/templates/components/ui/navbar.html
{#<nav>#}
{#    <ul class="flex lg:gap-8 sm:gap-4 text-center justify-center items-center text-md font-martian sm:text-sm">#}
{#        <li>#}
{#            <a href="{% url 'home' %}">Sobre Fetch</a>#}
{#        </li>#}
{#        <li>#}
{#            <a href="{% url 'post:post_detail' slug='festivales-de-chaco' %}">Eventos</a>#}
{#        </li>#}
{#        <li>#}
{#            <a href="{% url 'post:post_detail' slug='festivales-de-chaco' %}">Contactos</a>#}
{#        </li>#}
{##}
{#                <li>#}
{#                    <a href="{% url 'user:user_profile' %}">Perfil</a>#}
{#                </li>#}
{#        <li>#}
{#            {% include 'components/ui/buttonLogin.html' %}#}
{#        </li>#}
{##}
{#    </ul>#}
{#</nav>#}
<nav>
    <ul class="flex lg:gap-8 gap-4 text-center justify-center items-center text-md font-martian sm:text-sm">
        <li>
            <a href="{% url 'section_about' %}"  class="text-white hover:text-gray-300">Sobre Fetch</a>
        </li>
        <li>
            <a href="{% url 'post:post_list' %}" class="text-white hover:text-gray-300">Eventos</a>
        </li>
        <li>
            <a href="{% url 'section_contact' %}" class="text-white hover:text-gray-300">Contactos</a>
        </li>

         <li class="flex items-center button-container">
            <div class="hidden md:block"> 
                {% include 'components/ui/buttonLogin.html' %}
            </div>
            <div class="block md:hidden"> 
                {% include 'components/ui/button.html' %}
            </div>
        </li>


        <!-- Agregue esto como prueba para ver si funcionaba nms, hay que corregir -->
{#        {% if user.is_authenticated %}#}
{#            <!-- Mostrar opciones si el usuario está autenticado -->#}
{#            <li>#}
{#                <a href="{% url 'user:user_profile' %}">Perfil</a></li>#}
{#            <li>#}
{#                <form method="POST" action="{% url 'user:auth_logout' %}">#}
{#                    {% csrf_token %}#}
{#                    <button type="submit">Cerrar sesión</button>#}
{#                </form>#}
{#            </li>#}
{#        {% else %}#}
{#            <!-- Mostrar opciones si el usuario NO está autenticado -->#}
{#            <li><a href="{% url 'user:auth_login' %}">Iniciar sesión</a></li>#}
{#            <li><a href="{% url 'user:auth_register' %}">Registrarse</a></li>#}
{#        {% endif %}#}
{##}
{##}
{#        #}
{#        <li>#}
{#            {% include 'components/ui/buttonLogin.html' %}#}
{#        </li>#}
{#        #}

    </ul>
</nav>



{##}
{#        <!-- Agregue esto como prueba para ver si funcionaba nms, hay que corregir -->#}
{#        {% if user.is_authenticated %}#}
{#            <!-- Mostrar opciones si el usuario está autenticado -->#}
{#            <li>#}
{#                <a href="{% url 'user:user_profile' %}">Perfil</a></li>#}
{#            <li>#}
{#                <form method="POST" action="{% url 'user:auth_logout' %}">#}
{#                    {% csrf_token %}#}
{#                    <button type="submit">Cerrar sesión</button>#}
{#                </form>#}
{#            </li>#}
{#        {% else %}#}
{#            <!-- Mostrar opciones si el usuario NO está autenticado -->#}
{#            <li><a href="{% url 'user:auth_login' %}">Iniciar sesión</a></li>#}
{#            <li><a href="{% url 'user:auth_register' %}">Registrarse</a></li>#}
{#        {% endif %}#}
{##}
{##}
{#        #}
{#        <li>#}
{#            {% include 'components/ui/buttonLogin.html' %}#}
{#        </li>#}
{##}
{#    </ul>#}
{#</nav>#}

 