blog-django/blog/apps/post/urls.py
from django.urls import path
import apps.post.views as views

app_name = 'post'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('create', views.PostCreateView.as_view(), name='post_create'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/update', views.PostUpdateView.as_view(), name='post_update'),
    path('<slug:slug>/delete', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/<slug:slug>/comments/create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comments/<uuid:pk>/update/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comments/<uuid:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
]

blog-django/blog/apps/user/urls.py
from django.urls import path
import apps.user.views as views

app_name = "user"

urlpatterns = [
    path('profile/', views.UserProfileView.as_view(), name="user_profile"),
    path('auth/register/', views.RegisterView.as_view(), name="auth_register"),
    path('auth/login/', views.LoginView.as_view(), name="auth_login"),
    path('auth/logout/', views.LogoutView.as_view(), name="auth_logout"),
]

blog-django/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView, AuthLoginView, AuthRegisterView, AboutView, ContactView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('posts/', include('apps.post.urls', namespace='post')),
    path('users/', include('apps.user.urls', namespace='user')),
    #path('auth/login/', AuthLoginView.as_view(), name='auth_login'),
    #path('auth/register/', AuthRegisterView.as_view(), name='auth_register'),
    path('section/about/', AboutView.as_view(), name='section_about'),
    path('section/contact/', ContactView.as_view(), name='section_contact'),
]

if settings.DEBUG:
 from django.conf.urls.static import static
 # Sirviendo archivos estáticos
 urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
 # Sirviendo archivos media
 urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)
 
 '''
 from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView, AboutView 
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about')
    path('posts/', include('apps.post.urls', namespace='post')),
    path('user/', include('apps.user.urls', namespace='user'))
]

if settings.DEBUG:
 from django.conf.urls.static import static
 # Sirviendo archivos estáticos
 urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
 # Sirviendo archivos media
 urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)
 '''

blog-django/blog/apps/post/models.py
import os

from django.db import models
from django.utils import timezone
from django.conf import settings
from django.utils.text import slugify
import uuid


class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=200, blank=True)
    content = models.TextField(max_length=10000)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(default=timezone.now)
    modification_date = models.DateTimeField(auto_now=True)
    allow_comments = models.BooleanField(default=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='posts')
    location = models.ForeignKey('Location', on_delete=models.CASCADE, related_name='posts', default=1) #agrego de ubicacion como campo de post

    # blog/apps/post/models.py
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_unique_slug()
        super().save(*args, **kwargs)
        if not self.images.exists():
            PostImage.objects.create(post=self, image='post/default/post_default.png')

    def generate_unique_slug(self):
        # tenemos este titulo para el post
        # tenemos-este-titulo-para-el-post-1

        slug = slugify(self.title)
        unique_slug = slug
        num = 1

        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = f'{slug}-{num}'
            num += 1

        return unique_slug
    


class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    content = models.TextField(max_length=500)
    creation_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.content


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField(max_length=1000)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Location(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.name

def get_image_filename(instance, filename):
    post_id = instance.post.id
    images_count = instance.post.images.count()
    base_filename, file_extension = os.path.splitext(filename)  # esto se llama unpacking (desempaquetado)
    new_filename = f"post_{post_id}_cover_{images_count + 1}{file_extension}"
    return os.path.join('post/cover/', new_filename)


class PostImage(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=get_image_filename, default='post/default/post_default.png')
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"PostImage {self.id}"

blog-django/blog/apps/post/forms.py
from django import forms 
from apps.post.models import Post, PostImage, Comment

#Estructura formulario para crear nuevo post
class PostForm(forms.ModelForm): 
    class Meta: 
        model = Post 
        fields = ('title', 'content', 'category','location','allow_comments') 

class NewPostForm(PostForm): 
    image = forms.ImageField(required=False) 

    def save(self, commit=True): 
    # Guardar el post pero no aún en la base de datos ya que necesitamos el id del post para la imagen 
        post = super().save(commit=False) 
        if commit: 
            post.save()  # Guardar el post 
            if self.cleaned_data['image']: 
                PostImage.objects.create( 
                    post=post, image=self.cleaned_data['image'])  #Creamos la imagen 
        return post
    
class UpdatePostForm(PostForm): 
    image = forms.ImageField(required=False) 

    def __init__(self, *args, **kwargs): 
        # Obtenemos las imágenes activas del post que se quiere actualizar 
        self.active_images = kwargs.pop('active_images', None) 
        super(UpdatePostForm, self).__init__(*args, **kwargs) 
        
        if self.active_images: 
            for image in self.active_images: 
                # keep_image_1, keep_image_2, ... etc es el nombre del campo que se creará en el formulario para mantener la imagen activa 
                field_name = f"keep_image_{image.id}" 
                self.fields[field_name] = forms.BooleanField( 
                    required=False, initial=True, label=f"Mantener {image}" 
                ) 

    def save(self, commit=True): 
        post = super().save(commit=False) 
        if commit: 
            post.save() 
            if self.cleaned_data['image']:  # Si el usuario sube una nueva imagen 
                PostImage.objects.create( 
                    post=post, image=self.cleaned_data['image']) 

            if self.active_images:  # Si hay imágenes activas y se quiere mantener alguna 
                for image in self.active_images: 
                    if not self.cleaned_data.get(f"keep_image_{image.id}", True): 
                        image.delete()  # Eliminar la imagen si el usuario no la quiere mantener, checkboxes desmarcados 
        return post 

#Estructura formulario para crear nuevo comentario

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': 'Comentario'
            }
        widgets = {
            'content': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Escribe tu comentario...', 'class': 'p-2'})
        }

blog-django/blog/apps/post/views.py
from django.views.generic import TemplateView, ListView, CreateView, DetailView, DeleteView, UpdateView
from apps.post.models import Post, PostImage, Comment, Location, Category
from apps.post.forms import NewPostForm, UpdatePostForm, CommentForm
from django.urls import reverse, reverse_lazy
from django.conf import settings 
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

#Listar posts
class PostListView(ListView): 
    model = Post 
    template_name = 'post/post_list.html' 
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset()
        order_by = self.request.GET.get('order_by')
        location_id = self.request.GET.get('location')
        category_id = self.request.GET.get('category')

        if location_id:
            queryset = queryset.filter(location_id=location_id)
        if category_id:
            queryset = queryset.filter(category_id=category_id)

        if order_by:
            queryset = queryset.order_by(order_by)
        else:
            queryset = queryset.order_by('-creation_date')  # Ordenar por fecha de creación por defecto

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['locations'] = Location.objects.all()  # Obtener todas las ubicaciones
        context['categories'] = Category.objects.all()  # Obtener todas las categorías
        return context

    
#Crear post
class PostCreateView(CreateView): 
    model = Post 
    form_class = NewPostForm 
    template_name = 'post/post_create.html' 

    def form_valid(self, form): 
        form.instance.author = self.request.user 
        post = form.save() 

        images = self.request.FILES.getlist('images') 

        if images: 
            for image in images: 
                PostImage.objects.create(post=post, image=image) 
        else: 
            PostImage.objects.create(post=post, image=settings.DEFAULT_POST_IMAGE) 
    
        return super().form_valid(form) 
    
    def get_success_url(self): 
        return reverse('post:post_detail', kwargs={'slug': self.object.slug}) 
    
#Ver un post en detalle
class PostDetailView(DetailView): 
    model = Post
    template_name = 'post/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        active_images = self.object.images.filter(active=True)
        context['active_images'] = active_images
        context['add_comment_form'] = CommentForm()

        # Editar comentario
        edit_comment_id = self.request.GET.get('edit_comment')
        if edit_comment_id:
            comment = get_object_or_404(Comment, id=edit_comment_id)
        # Permitimos editar solo si el usuario logueado es el autor del comentario
            if comment.author == self.request.user:
                context['editing_comment_id'] = comment.id
                context['edit_comment_form'] = CommentForm(instance=comment)
            else:
                context['editing_comment_id'] = None
                context['edit_comment_form'] = None

        # Eliminar comentario
        delete_comment_id = self.request.GET.get('delete_comment')
        if delete_comment_id:
            comment = get_object_or_404(Comment, id=delete_comment_id)
            # Permitimos solo si el usuario logueado tiene permiso para eliminar el comentario
            if (
                # Es autor del comentario
                comment.author == self.request.user or
                # Es autor del post, pero el comentario no es de un admin o un superuser
                (comment.post.author == self.request.user and not comment.author.is_admin and not comment.author.is_superuser) or
                self.request.user.is_superuser or  # Es Superuser
                self.request.user.groups.filter(name='Admins').exists()  # Es Admin
            ):
                context['deleting_comment_id'] = comment.id
            else:
                context['deleting_comment_id'] = None
        return context

#Actualizar post
class PostUpdateView(UpdateView): 
    model = Post 
    form_class = UpdatePostForm 
    template_name = 'post/post_update.html' 

    def get_form_kwargs(self): 
        kwargs = super().get_form_kwargs() 
        kwargs['active_images'] = self.get_object().images.filter(active=True)  # Pasamos las imágenes activas 
        return kwargs 
    
    def form_valid(self, form): 
        post = form.save(commit=False) 
        active_images = form.active_images 
        keep_any_image_active = False 
    
    # Manejo de las imágenes activas 
        if active_images: 
            for image in active_images: 
                field_name = f"keep_image_{image.id}" 
                # Si el checkbox no está marcado, eliminamos la imagen 
                if not form.cleaned_data.get(field_name, True): 
                    image.active = False 
                    image.save() 
                else: 
                    keep_any_image_active = True 

    # Manejo de las nuevas imágenes subidas 
        images = self.request.FILES.getlist('images') 
        if images: 
            for image in images: 
                    PostImage.objects.create(post=post, image=image) 

    # Si no se desea mantener ninguna imagen activa y no se subieron nuevas imágenes, 
    # se agrega una imagen por defecto 
        if not keep_any_image_active and not images: 
            PostImage.objects.create( 
                post=post, image=settings.DEFAULT_POST_IMAGE) 
            post.save()  # Guardar el post finalmente 
            return super().form_valid(form) 
    
    def get_success_url(self): 
    #El reverse_lazy es para que no se ejecute hasta que se haya guardado el post 
        return reverse_lazy('post:post_detail', kwargs={'slug': self.object.slug})

#Eliminar posts
class PostDeleteView(DeleteView):
    model = Post 
    template_name = 'post/post_delete.html' 
    success_url = reverse_lazy('post:post_list') 

#Crear Comentario
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'post/post_detail.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = Post.objects.get(slug=self.kwargs['slug'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('post:post_detail', kwargs={'slug':
        self.object.post.slug})
    
#Actualizar Comentario
class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'post/post_detail.html'
    login_url = reverse_lazy('user:auth_login')

    def get_object(self):
        return get_object_or_404(Comment, id=self.kwargs['pk'])

    def get_success_url(self):
        return reverse_lazy('post:post_detail', kwargs={'slug':
        self.object.post.slug})

    def test_func(self):
        comment = self.get_object()
        return comment.author == self.request.user

#Eliminar Comentario
class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    login_url = reverse_lazy('user:auth_login')

    def get_object(self):
        return get_object_or_404(Comment, id=self.kwargs['pk'])
    
    def get_success_url(self):
        return reverse_lazy('post:post_detail', kwargs={'slug':
        self.object.post.slug})
    
    def test_func(self):
        comment = self.get_object()

        is_comment_author = self.request.user == comment.author

        is_post_author = (
            self.request.user == comment.post.author and
            not comment.author.is_admin and
            not comment.author.is_superuser
        )
        is_admin = self.request.user.is_superuser or self.request.user.groups.filter(
            name='Admins').exists()
        return is_comment_author or is_post_author or is_admin

blog-django/blog/templates/post/post_create.html
{% extends 'layouts/post_layout.html' %}  

{% block title %}Post | BLOG FeCh{% endblock title %} 

{% block content %} 


    <h2>Crear nuevo post</h2>
    <form method="post" enctype="multipart/form-data"> 
    {% csrf_token %} 
        <div class="flex flex-col gap-4"> 
            <p class="flex flex-col">{{ form.title.label_tag }} {{ form.title }}</p> 
            <p class="flex flex-col"> 
                <label for="id_content">Contenido:</label> {{ form.content }} {{ form.category }} {{ form.location }}</p> 
            <p>{{ form.allow_comments.label_tag }} {{ form.allow_comments }}</p> 
            <p><input type="file" name="images" multiple /></p> 
        </div> 

        <button type="submit" class="bg-blue-500 text-white p-2 rounded-lg"> 
            Crear Post 
        </button>
    </form> 

{% endblock content %}

blog-django/blog/templates/post/post_delete.html
{% extends 'layouts/post_layout.html' %} 

{% block title %}BORRAR Post | BLOG FeCh{% endblock title %} 

{% block content %} 
<h2>¿Estás seguro de que deseas eliminar este post?</h2>
 <form method="post"> 
    {% csrf_token %} 
    <button type="submit">Sí, eliminar</button>
 </form> 

<a href="{% url 'post:post_detail' slug=object.slug %}">Cancelar</a> 
{% comment %} <a href="javascript:history.back()">Cancelar</a> {% endcomment %} 

{% endblock content %}

blog-django/blog/templates/post/post_detail.html
{% extends 'layouts/post_layout.html' %} 

{% block title %}Post | BLOG FeCh{% endblock title %} 

{% block content %} 

{% if active_images %} 
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4"> 
        {% for image in active_images %} 
            <img src="{{ image.image.url }}" alt="Portada del post" class="w-[400px] object-cover aspect-[16/9]" /> 
        {% endfor %} 
    </div> 
{% endif %} 

<h3 class="text-2xl uppercase font-bold">{{ post.title }}</h3> 

<p>{{ post.content }}</p>
<p>Publicado por: <strong class="font-bold">{{ post.author.username }}</strong></p>
<p>Fecha de publicación: {{ post.creation_date }}</p>
<p>Comentarios permitidos: {{ post.allow_comments|yesno:"Si,No" }}</p>
<div class="flex mt-8 gap-4"> 
    <a 
        class="bg-blue-500 text-white p-2 rounded-lg" 
        href="{% url 'post:post_update' slug=post.slug %}" 
    >Editar post</a> 
    <a 
        class="bg-red-500 text-white p-2 rounded-lg" 
        href="{% url 'post:post_delete' slug=post.slug %}" 
    >Eliminar post</a>
</div> 

<!-- Listado de comentarios -->
<h4 class="mt-8 mb-4">Comentarios</h4>
{% if post.comments.count > 0 %}
    <ul>
        {% for comment in post.comments.all %}
            <li class="mb-8">
                {% if comment.id == editing_comment_id %}
                    <!-- Formulario de actualización -->
                    <form method="post" action="{% url 'post:comment_update' comment.id %}">
                        {% csrf_token %}
                        <p class="flex flex-col">{{ edit_comment_form.content.label_tag }} {{ edit_comment_form.content }}</p>
                        <button type="submit" class="text-blue-500">Actualizar</button>
                        <a href="{% url 'post:post_detail' post.slug %}" class="text-red-500">Cancelar</a>
                    </form>
                {% elif comment.id == deleting_comment_id %}
                    <!-- Formulario de confirmación de eliminación -->
                    <form method="post" action="{% url 'post:comment_delete' comment.id %}">
                        {% csrf_token %}
                        <p>¿Estás seguro de que deseas eliminar este comentario?</p>
                        <button type="submit" class="text-blue-500">Confirmar</button>
                        <a href="{% url 'post:post_detail' post.slug %}" class="text-red-500">Cancelar</a>
                    </form>
                {% else %}
                    <!-- Comentario -->
                    <p>{{ comment.content }}</p>
                    <small>Escrito por <strong>{{ comment.author.username }}</strong> el {{ comment.creation_date }}</small>
                    {% if comment.author == user %}
                        <a href="?edit_comment={{ comment.id }}" class="text-blue-500">Editar</a>
                        <a href="?delete_comment={{ comment.id }}" class="text-red-500">Eliminar</a>
                    {% elif user.is_collaborator and post.author == user and not comment.author.is_admin and not comment.author.is_superuser or user.is_superuser or user.is_admin %}
                        <a href="?delete_comment={{ comment.id }}" class="text-red-500">Eliminar</a>
                    {% endif %}
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay comentarios aún.</p>
{% endif %}

{% if user.is_authenticated %}
    <h4>Agregar un comentario</h4>
    <form method="post" action="{% url 'post:comment_create' post.slug %}">
        {% csrf_token %}
        <p class="flex flex-col mt-4 mb-8">{{ add_comment_form.content.label_tag }} {{ add_comment_form.content }}</p>
        <button type="submit" class="bg-blue-500 text-white p-2 rounded-lg">Agregar comentario</button>
    </form>
{% else %}
    <p>
        <a href="{% url 'user:auth_login' %}?next={{ request.path }}" class="hover:text-blue-500">
            Inicia sesión
        </a>
        para agregar un comentario.
    </p>
{% endif %}

{% endblock content %}

blog-django/blog/templates/post/post_list.html
{% extends 'layouts/post_layout.html' %} 

{% block title %}Post | BLOG FeCh{% endblock title %} 

{% block content %} 
    <div class="mb-4">
        <form method="GET" class="flex flex-col sm:flex-row gap-4">
            <div>
                <label for="location" class="block text-white">Ubicación:</label>
                <select name="location" id="location" class="p-2 rounded">
                    <option value="">--Seleccionar ubicación--</option>
                    {% for location in locations %}
                        <option value="{{ location.id }}"{% if request.GET.location == location.id %} selected{% endif %}>{{ location.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div>
                <label for="category" class="block text-white">Categoría:</label>
                <select name="category" id="category" class="p-2 rounded">
                    <option value="">--Seleccionar categoría--</option>
                    {% for category in categories %}
                        <option value="{{ category.id }}"{% if request.GET.category == category.id %} selected{% endif %}>{{ category.title }}</option>
                    {% endfor %}
                </select>
            </div>

            <div>
                <label for="order_by" class="block text-white">Ordenar por:</label>
                <select name="order_by" id="order_by" class="p-2 rounded">
                    <option value="creation_date" {% if request.GET.order_by == "creation_date" %} selected{% endif %}>Fecha de creación</option>
                    <option value="title" {% if request.GET.order_by == "title" %} selected{% endif %}>Título</option>
                </select>
            </div>

            <button type="submit" class="bg-blue-500 text-white p-2 rounded">Filtrar y Ordenar</button>
        </form>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {% if posts %}
         {% for post in posts %}
             {% include 'components/ui/card.html' with title=post.title description=post.location date=post.creation_date allow_comments=post.allow_comments|yesno:"Si,No" user=post.author.username %}
         {% endfor %}
        {% else %}
            <p class="text-white">No hay posts disponibles.</p>
        {% endif %}
    </div>
{% endblock content %}

blog-django/blog/templates/post/post_update.html
{% extends 'layouts/post_layout.html' %} 

{% block title %}ACTUALIZAR Post | BLOG FeCh{% endblock title %} 

{% block content %} 
<h2>Actualizar: {{ form.instance.title }}</h2> 

<form 
    method="post" 
    enctype="multipart/form-data" 
    class="flex flex-col justify-center items-start w-[400px] gap-4" 
> 
  {% csrf_token %} 
    <div class="flex flex-col">{{ form.title.label_tag }} {{ form.title }}</div> 
    <div class="flex flex-col"> 
        {{ form.content.label_tag }} {{ form.content }} 

    </div> 
    <div class="flex gap-4"> 
        {{ form.allow_comments.label_tag }} {{ form.allow_comments }} 
    </div> 

    <h3>Imágenes cargadas</h3> 

    <div class="flex flex-col gap-4"> 
        {% for active_img in form.active_images %}  
        {% comment %} <p>{{ active_img.id }}</p> {% endcomment %}  
        {% comment %} <p>{{ active_img.post }}</p> {% endcomment %}  
        {% comment %} <p>{{ active_img.post.author }}</p> {% endcomment %}  
        {% comment %} <p>{{ active_img.image }}</p> {% endcomment %}  
        {% comment %} <p>{{ active_img.image.url }}</p> {% endcomment %}  
        {% comment %} <p>{{ active_img.active }}</p> {% endcomment %}  
        {% comment %} <p>{{ active_img.creation_date }}</p> {% endcomment %} 
        <p> 
            <a href="{{ active_img.image.url }}" target="_blank"> 
                <img 
                    class="inline-flex w-[200px] aspect-[16/9] object-cover" 
                    src="{{ active_img.image.url }}" 
                    alt="Portada {{ active_img.id }} del post" 
                /> 
            </a> 
            <input 
                type="checkbox" 
                name="keep_image_{{ active_img.id }}" 
                id="keep_image_{{ active_img.id }}" 
                checked 
            /> 
            <label for="keep_image_{{ active_img.id }}">Activa</label> 
        </p> 
        {% endfor %} 
    </div> 

    <h3>Cargar nuevas imágenes</h3> 

    <input type="file" name="images" multiple /> 
    <div class="flex gap-2"> 
        <a href="{% url 'post:post_detail' slug=form.instance.slug %}" 
            class="bg-red-500 text-white p-2 rounded-md">Cancelar</a> 
        <button type="submit" class="bg-blue-500 text-white p-2 rounded-md"> 
             Guardar cambios 
        </button> 
    </div>
 </form> 

{% comment %} <a href="javascript:history.back()">Cancelar</a> {% endcomment %} 

{% endblock content %} 